src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Security\Core\User\UserInterface;

/**
 * @ORM\Entity
 * @ORM\Table(name="user")
 */
class User implements UserInterface
{
    public function __toString()
    {
        return $this->getFullName();
    }

    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private ?int $id = null;

    /**
     * @ORM\Column(type="string", length=180, unique=true)
     */
    private string $username;

    /**
     * @ORM\Column(type="json")
     */
    private array $roles = [];

    /**
     * @var string The hashed password
     * @ORM\Column(type="string")
     */
    private string $password;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private string $first_name;

    /**
     * @var string
     * @ORM\Column(type="string")
     */
    private string $last_name;

    /**
     * @ORM\Column(type="boolean", nullable=true,options={"default": false})
     */
    private bool $is_job_pool = false;


    // Implementación de los métodos de UserInterface
    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): string
    {
        return $this->username;
    }

    public function setUsername(string $username): self
    {
        $this->username = $username;

        return $this;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        // garantizar que siempre haya al menos un rol
        $roles[] = 'ROLE_USER';

        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;

        return $this;
    }

    public function getPassword(): string
    {
        return $this->password;
    }

    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    public function isJobPool(): bool {
        return $this->is_job_pool;
    }

    public function setJobPool(bool $is_job_pool): void {
        $this->is_job_pool = $is_job_pool;
    }

    public function getSalt(): ?string
    {
        // No necesaria si utilizas bcrypt o argon2i
        return null;
    }

    public function eraseCredentials()
    {
        // Si almacenas información sensible temporalmente en el objeto, límpiala aquí
    }

    // Otros métodos que quieras implementar, como getters y setters para firstName, lastName, etc.
    public function getFirstName(): string
    {
        return $this->first_name;
    }

    public function setFirstName(string $first_name): void
    {
        $this->first_name = $first_name;
    }

    public function getLastName(): string
    {
        return $this->last_name;
    }

    public function setLastName(string $last_name): void
    {
        $this->last_name = $last_name;
    }

    public function getFullName(): string
    {
        return $this->first_name . ($this->last_name ? " " . $this->last_name : "");
    }
}

src/Controller/API/V1/TraceabilityController.php
<?php

namespace App\Controller\API\V1;

use App\Repository\ArticleRepository;
use App\Repository\MovementRepository;
use App\Repository\UserRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/api/v1/traceability", name="traceability_")
 */
class TraceabilityController extends AbstractController
{
    private $security;

    public function __construct(Security $security)
    {
        $this->security = $security;
    }



    /**
     * @Route("/by-serial-number/{serial}", name="by_serial_number", methods={"GET"})
     */
    public function getTraceabilityBySerialNumber(string $serial, ArticleRepository $articleRepository, MovementRepository $movementRepository): Response
    {
        $article = $articleRepository->findOneBy(['serialNumber' => $serial]);

        if (!$article) {
            return $this->json(['message' => 'Article not found'], Response::HTTP_NOT_FOUND);
        }

        $movements = $movementRepository->findBy(['article' => $article]);

        // Aquí deberías transformar $movements a DTOs o arrays como prefieras antes de devolverlos

        return $this->json($movements);
    }

    /**
     * @Route("/by-worker/{id}", name="by_worker", methods={"GET"})
     */
    public function getTraceabilityByWorker(int $id, MovementRepository $movementRepository): Response
    {
        $movements = $movementRepository->findByWorker($id);

        // Aquí deberías transformar $movements a DTOs o arrays como prefieras antes de devolverlos

        return $this->json($movements);
    }

    // Implementa los métodos adicionales si es necesario
}

src/Controller/TraceabilityController.php
<?php

namespace App\Controller;

use App\Entity\Article;
use App\Entity\ArticleJobTimeEntry;
use App\Entity\Movement;
use App\Repository\ArticleJobTimeEntryRepository;
use App\Repository\ArticleRepository;
use App\Repository\JobTypeRepository;
use App\Repository\MovementRepository;
use App\Repository\UserRepository;
use App\Service\BoxService;
use App\Service\ExcelGenerator;
use App\Service\XGestRestClient;
use DateTime;
use Develia\Date;
use Develia\From;
use Develia\TimeSpan;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Security\Core\Security;

/**
 * @Route("/traceability",name="app_traceability_")
 */
class TraceabilityController extends AbstractController {
    private UserRepository $userRepository;
    private MovementRepository $movementRepository;
    private ArticleRepository $articleRepository;
    private Security $security;
    private JobTypeRepository $jobTypeRepository;
    private BoxService $boxService;
    private ArticleJobTimeEntryRepository $articleJobTimeEntryRepository;
    private ExcelGenerator $excelGenerator;

    public function __construct(UserRepository                $userRepository,
                                JobTypeRepository             $jobTypeRepository,
                                MovementRepository            $movementRepository,
                                ArticleRepository             $articleRepository,
                                Security                      $security,
                                ArticleJobTimeEntryRepository $articleJobTimeEntryRepository,
                                BoxService                    $boxService,
                                ExcelGenerator                $excelGenerator) {

        $this->userRepository = $userRepository;

        $this->movementRepository = $movementRepository;
        $this->articleRepository = $articleRepository;
        $this->security = $security;
        $this->jobTypeRepository = $jobTypeRepository;
        $this->boxService = $boxService;
        $this->articleJobTimeEntryRepository = $articleJobTimeEntryRepository;
        $this->excelGenerator = $excelGenerator;
    }

    /**
     * @Route("/boxes",name="boxes")
     */
    public function index(Request $request) {
        return $this->render('traceability/boxes.html.twig', []);
    }

    /**
     * @Route("/by-imei",name="by_imei")
     */
    public function byImei(Request $request) {


        $movements = null;
        $owner = null;
        $receiver = null;
        $serialNumber = null;
        $job = null;
        $deliveryNoteId = null;
        $description = null;
        $code = null;
        $customer = null;

        if ($request->getMethod() == "POST") {
            $serialNumber = $request->request->get("serialNumber");
            $movements = from($this->movementRepository->findBySerialNumber($serialNumber))
                ->orderBy(fn(Movement $x) => $x->getDate(), "desc")
                ->toArray(false);

            if ($article = $this->articleRepository->findOneBySerialNumber($serialNumber)) {
                if ($owner = $article->getOwner()) {
                    $owner = $owner->getFirstName() . " " . $owner->getLastName();
                }

                if ($receiver = $article->getReceiver()) {
                    $receiver = $receiver->getFirstName() . " " . $receiver->getLastName();
                }

                if ($jobType = $article->getJobType()) {
                    $job = $jobType->getDescription();
                }

                $description = $article->getDescription();
                $code = $article->getCode();
                $deliveryNoteId = $article->getDeliveryNoteId();
                $customer = $article->getCustomer();

            }
        }


        return $this->render('traceability/by-imei.html.twig', [
            "owner"          => $owner,
            "receiver"       => $receiver,
            "serialNumber"   => $serialNumber,
            "job"            => $job,
            "deliveryNoteId" => $deliveryNoteId,
            "description"    => $description,
            "code"           => $code,
            "customer"       => $customer,
            "articleUpdates" => $movements
        ]);
    }

    /**
     * @Route("/by-order",name="by_order")
     */
    public function byOrder(Request $request) {


        $deliveryNoteId = $request->request->get("deliveryNoteId");
        if ($request->getMethod() == "POST") {

            $articles = $this->articleRepository->findByDeliveryOrder($deliveryNoteId);
        } else {
            $articles = [];
        }


        return $this->render('traceability/by-order.html.twig', [
            "articles"       => from($articles)->map(fn($x) => $this->articleToDTO($x))->toArray(),
            "deliveryNoteId" => $deliveryNoteId
        ]);
    }

    /**
     * @param $x
     * @param mixed $jobType
     * @param mixed $owner
     * @param mixed $receiver
     * @return array
     */
    private function articleToDTO(Article $x): array {
        $jobType = $x->getJobType();
        $owner = $x->getOwner();
        $receiver = $x->getReceiver();

        return [
            "code"                  => $x->getCode(),
            "description"           => $x->getDescription(),
            "id"                    => $x->getId(),
            "customer"              => $x->getCustomer(),
            "delivery_note_id"      => $x->getDeliveryNoteId(),
            "serial_number"         => $x->getSerialNumber(),
            "job_type_id"           => $jobType?->getId(),
            "job_type_description"  => $jobType?->getDescription(),
            "owner_id"              => $owner?->getId(),
            "owner_display_name"    => $owner ? $owner->getFirstName() . " " . $owner->getLastName() : null,
            "receiver_id"           => $receiver?->getId(),
            "receiver_display_name" => $receiver ? $receiver->getFirstName() . " " . $receiver->getLastName() : null,
        ];
    }

    /**
     * @Route("/by-technician",name="by_technician")
     */
    public function byTechnician(Request $request) {
        $technician = $request->request->get("technician");
        $deliveryNoteId = $request->request->get("deliveryNoteId");
        $serialNumber = $request->request->get("serialNumber");

        if ($request->getMethod() == "POST") {

            $fromDate = null;
            if ($fromDateStr = $request->request->get("fromDate")) {
                $fromDate = Date::startOfDay(DateTime::createFromFormat('Y-m-d', $fromDateStr));
            }

            $toDate = null;
            if ($toDateStr = $request->request->get("toDate")) {
                $toDate = Date::endOfDay(DateTime::createFromFormat('Y-m-d', $toDateStr));
            }

            $movements = from($this->movementRepository->findByTechnician($technician, $fromDate, $toDate))
                ->orderBy(fn(Movement $x) => $x->getDate(), "desc")
                ->toArray(false);
            if ($deliveryNoteId) {
                $movements = from($movements)->filter(fn(Movement $x) => $x->getArticle()->getDeliveryNoteId() == $deliveryNoteId)->toArray(false);
            }

            if ($serialNumber) {
                $movements = from($movements)->filter(fn(Movement $x) => $x->getArticle()->getSerialNumber() == $serialNumber)->toArray(false);
            }

        } else {
            $movements = [];
        }


        return $this->render('traceability/by-technician.html.twig', [
            "articleUpdates" => $movements,
            "technicians"    => $this->userRepository->findAll(),
            'technician'     => $technician,
            'boxes'          => $technician ? $this->boxService->getBoxes($technician) : null,
            "deliveryNoteId" => $deliveryNoteId,
            "serialNumber"   => $serialNumber
        ]);
    }

    /**
     * @Route("/import-from-xgest", name="import_from_xgest", methods={"GET","POST"})
     */
    public function importFromXGest(Request $request, XGestRestClient $xGestHttpClient, EntityManagerInterface $em) {
        return $this->render('traceability/import-from-xgest.html.twig', []);
    }

    /**
     * @Route("/performance-excel", name="performance_excel", methods={"GET","POST"})
     */
    public function performace_excel(\Develia\Request $request) {


        $form = $request->getForm();
        if ($request->getMethod() == 'POST' && $form->tryGetInt("technician", $technicianId)) {

            $fromDate = $form->tryGetDate("fromDate", $fromDate) ? Date::startOfDay($fromDate) : null;
            $toDate = $form->tryGetDate("toDate", $toDate) ? Date::endOfDay($toDate) : null;

            $this->excelGenerator->generate_performance_excel($technicianId, $fromDate, $toDate);

        }
    }

    /**
     * @Route("/performance", name="performance", methods={"GET","POST"})
     */
    public function performance(Request $request) {


        $technicianId = null;
        $performance = null;

        $fromDateStr = null;
        $toDateStr = null;

        if ($request->getMethod() == 'POST') {

            $technicianId = $request->request->get("technician");

            $fromDate = null;
            if ($fromDateStr = $request->request->get("fromDate")) {
                $fromDate = Date::startOfDay(DateTime::createFromFormat('Y-m-d', $fromDateStr));
            }

            $toDate = null;
            if ($toDateStr = $request->request->get("toDate")) {
                $toDate = Date::endOfDay(DateTime::createFromFormat('Y-m-d', $toDateStr));
            }

            $performance = $this->boxService->getPerformance($technicianId, $fromDate, $toDate);

        }


        if ($this->security->isGranted("ROLE_TECHNICIAN_SUPERVISOR")) {
            $technicians = $this->userRepository->findAll();

templates/traceability/boxes.html.twig
{% extends '/backend.html.twig' %}
{% block content %}
    <Boxes></Boxes>
{% endblock %}
                                {% block toolbar %}
                                    <a href="{{ path('app_traceability_import_from_xgest') }}" class="btn-primary btn">Importar desde XGest</a>
                                {% endblock %}

templates/traceability/by-imei.html.twig
{% extends '/backend.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2>Trazabilidad por IMEI</h2>
        </div>
    </div>
    <form class="row" method="post">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <div class="mb-3">
                        <label class="form-label">IMEI</label>
                        <input type="text" name="serialNumber" class="form-control" value="{{ serialNumber }}">
                    </div>

                    <div>
                        <button type="submit" class="btn btn-primary" style="width: 100%">Buscar</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            {% if serialNumber %}
                <div class="card">
                    <div class="card-header">
                        <h5 class="m-0 p-0">{{ deliveryNoteId }}</h5>
                        <small>{{ customer }}</small>
                    </div>
                    <div class="card-body">

                        <div class="row mb-3">
                            <label class="col-sm-2 col-form-label">Descripción</label>
                            <div class="col-sm-4 mb-3">
                                <input type="text" class="form-control" readonly="readonly" value="{{ description }}">
                            </div>
                            <label class="col-sm-2 col-form-label">Código</label>
                            <div class="col-sm-4 mb-3">
                                <input type="text" class="form-control" readonly="readonly" value="{{ code }}">
                            </div>
                            {% if owner %}

                                <label class="col-sm-2 col-form-label">Propietario</label>
                                <div class="col-sm-4 mb-3">
                                    <input type="text" class="form-control" readonly="readonly" value="{{ owner }}">
                                </div>

                            {% endif %}
                            {% if receiver %}

                                <label class="col-sm-2 col-form-label">Esperando aceptación de</label>
                                <div class="col-sm-4  mb-3">
                                    <input type="text" class="form-control" readonly="readonly" value="{{ owner }}">
                                </div>

                            {% endif %}
                            {% if job %}

                                <label class="col-sm-2 col-form-label">Tarea</label>
                                <div class="col-sm-4  mb-3">
                                    <input type="text" class="form-control" readonly="readonly" value="{{ job }}">
                                </div>

                            {% endif %}
                        </div>

                    </div>
                    {% if articleUpdates is not null %}
                        <table class="table table-compact">
                            <thead>
                                <tr>
                                    <th>Fecha</th>
                                    <th>Acción</th>
                                </tr>
                            </thead>

                            <tbody>
                                {% for movement in articleUpdates %}
                                    <tr>
                                        <td>{{ movement.date | date("Y-m-d H:i:s") }}</td>
                                        <td>
                                            {% if (movement.newOwner is not null and movement.oldOwner is null) %}
                                                <div class="row">
                                                    <div class="col-xl-3">
                                                        <b>Importación</b>
                                                    </div>
                                                    <div class="col-xl-9">

                                                    </div>

                                                </div>
                                            {% endif %}
                                            {% if (movement.newReceiver is not null) %}
                                                <div class="row">
                                                    <div class="col-xl-3">
                                                        <b>Propuesta de transferencia</b>
                                                    </div>
                                                    <div class="col-xl-9">
                                                        <div class="row">
                                                            <div class="col-xl-5" style="text-align: right">
                                                                {% if movement.oldOwner is not null %}
                                                                    <span>{{ movement.oldOwner.fullName }}</span>
                                                                {% else %}
                                                                    <span>Ninguno</span>
                                                                {% endif %}
                                                            </div>
                                                            <div class="col-xl-2" style="text-align: center">
                                                                <i class="fa fa-arrow-right"></i>
                                                            </div>
                                                            <div class="col-xl-5">
                                                                {% if movement.newReceiver is not null %}
                                                                    <span>{{ movement.newReceiver.fullName }}</span>
                                                                {% else %}
                                                                    <span>Ninguno</span>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>
                                            {% elseif (movement.newOwner is not null and movement.oldOwner is not null) %}
                                                <div class="row">
                                                    <div class="col-xl-3">
                                                        <b>Transferencia aceptada </b>
                                                    </div>
                                                    <div class="col-xl-9">
                                                        <div class="row">
                                                            <div class="col-xl-5" style="text-align: right">
                                                                {% if movement.oldOwner is not null %}
                                                                    <span>{{ movement.oldOwner.fullName }}</span>
                                                                {% else %}
                                                                    <span>Ninguno</span>
                                                                {% endif %}
                                                            </div>
                                                            <div class="col-xl-2" style="text-align: center">
                                                                <i class="fa fa-arrow-right"></i>
                                                            </div>
                                                            <div class="col-xl-5">
                                                                {% if movement.newOwner is not null %}
                                                                    <span>{{ movement.newOwner.fullName }}</span>
                                                                {% else %}
                                                                    <span>Ninguno</span>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>
                                            {% endif %}

                                            {% if (movement.newJobType is not null or movement.oldJobType is not null) and movement.newJobType is not same as movement.oldJobType %}
                                                <div class="row">
                                                    <div class="col-xl-3">
                                                        <b>{% if(movement.newJobType.finishes) %}
                                                                Tarea completada
                                                            {% else %}
                                                                Tarea actualizada
                                                            {% endif %}</b>
                                                    </div>
                                                    <div class="col-xl-9">
                                                        <div class="row">
                                                            <div class="col-xl-5" style="text-align: right">
                                                                {% if movement.oldJobType is not null %}
                                                                    <span>{{ movement.oldJobType.description }}</span>
                                                                {% else %}
                                                                    <span>Ninguna</span>
                                                                {% endif %}
                                                            </div>
                                                            <div class="col-xl-2" style="text-align: center">
                                                                <i class="fa fa-arrow-right"></i>
                                                            </div>
                                                            <div class="col-xl-5">
                                                                {% if movement.newJobType is not null %}
                                                                    <span>{{ movement.newJobType.description }}</span>
                                                                {% else %}
                                                                    <span>Ninguna</span>
                                                                {% endif %}
                                                            </div>
                                                        </div>
                                                    </div>

                                                </div>
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    {% endif %}

                </div>
            {% endif %}
        </div>
    </form>
{% endblock %}

{% block toolbar %}

{% endblock %}

templates/traceability/by-order.html.twig
{% extends '/backend.html.twig' %}

{% block content %}
    <div class="row">
        <div class="col-md-12">
            <h2>Trazabilidad por pedido</h2>
        </div>
    </div>
    <form class="row" method="post">
        <div class="col-md-3">
            <div class="card">
                <div class="card-body">
                    <div class="mb-3">
                        <label class="form-label">Nº Pedido</label>
                        <input type="text" name="deliveryNoteId" class="form-control" value="{{ deliveryNoteId }}">
                    </div>

                    <div>
                        <button type="submit" class="btn btn-primary" style="width: 100%">Buscar</button>
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-9">
            {% if deliveryNoteId %}
                <div class="card">
                    <Box :items="{{ articles | json_encode  }}"></Box>
                </div>
            {% endif %}
        </div>
    </form>
{% endblock %}

{% block toolbar %}

{% endblock %}

templates/traceability/import-from-xgest.html.twig
{% extends '/backend.html.twig' %}

{% block content %}

    <div class="row">
        <div class="col-md-12">
            <h2>Importar desde XGest</h2>
        </div>
        <div class="col-md-12">
            <ImportFromXGest></ImportFromXGest>
        </div>
    </div>


{% endblock %}

        {% block scripts %}

            <script>
                document.addEventListener("DOMContentLoaded", function () {
                    for (let row of document.querySelectorAll("tr")) {

                        let id = row.getAttribute("data-id");
                        for (let button of row.querySelectorAll(" button[type=button]")) {
                            button.addEventListener("click", function () {
                                let data = {
                                    deliveryNoteId: row.querySelector("[name='import[" + id + "][identifier]']").value,
                                    line: row.querySelector("[name='import[" + id + "][line]']").value,
                                    technician: row.querySelector("[name='import[" + id + "][technician]']").value,
                                    jobType: row.querySelector("[name='import[" + id + "][job]']").value,
                                    priority: row.querySelector("[name='import[" + id + "][priority]']").value,
                                }

                                row.remove();
                            })
                        }
                    }
                });
            </script>
        {% endblock %}